name: unit-test

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/**"
      - "df_psm/**"

jobs:
  cLang:
    name: c
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install editline
        run: |
          wget https://github.com/troglobit/editline/releases/download/1.17.1/editline-1.17.1.tar.gz
          tar xf editline-1.17.1.tar.xz
          cd editline-1.17.1/
          ./configure --prefix=/usr
          make all
          sudo make install

      - name: build
        run: cmake -S ./ -B build

      - run: cmake --build build

      - name: run test
        run: cd build && ctest
